### ISSUE TITLE
Complete code

### ISSUE THREAD

**Issue by zxt-triumph** [DeweiHu/OCT_DDPM#1]
First of all, thank you very much for your work, I hope you can open source the complete code, including training, testing, etc. If it is not convenient to open source, Could you send it to me privately, thank you very much.

**Comment by DeweiHu** [comment]
Yes of course, I need to re-arrange my code and I will send you a notice when I have it available.

Thanks for your interest.

Dewei
________________________________
From: zxt-triumph ***@***.***>
Sent: Friday, June 24, 2022 2:43 AM
To: DeweiHu/OCT_DDPM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DeweiHu/OCT_DDPM] Complete code (Issue #1)


First of all, thank you very much for your work, I hope you can open source the complete code, including training, testing, etc. If it is not convenient to open source, Could you send it to me privately, thank you very much.

**Comment by ForAriza** [comment]
@DeweiHu Thank you for your share.I am very interested in your work  in paper _Unsupervised Denoising of Retinal OCT with Diffusion_,and if posible I hope you can share complete code or just send it to me privately so that I can learn more details.Thank you for your share,again.

**Comment by DeweiHu** [comment]
Hello,

Thank you for your interest! I uploaded the code I was using for model setting, pre-processing, training and testing in /src/. I am sorry that I didn't get time to clean the code. Please let me know if you need anything.

Thanks,
Dewei

**Comment by DeweiHu** [comment]
Hello,

Thank you for your interest! I uploaded the code I was using for model setting, pre-processing, training and testing in /src/. I am sorry that I didn't get time to clean the code. Please let me know if you need anything.

Thanks,
Dewei
________________________________

**Comment by jasonhu4** [comment]
Thanks very much for sharing the code! I just wanted to clarify one thing, which is that in trainDataset, the data loader should load noisy images (not clean images), correct? So the network can learn from noisy images of various different SNR levels and does not require any clean data at all.

**Comment by DeweiHu** [comment]
That's correct, there is no clean data involved.

Dewei
________________________________
