### ISSUE TITLE
Paper's dataset

### ISSUE THREAD

**Issue by xwt11** [DeweiHu/OCT_DDPM#4]
Thank you for your excellent work and sharing the code.
Is the dataset in the paper public or private? 
If it is public, can you provide the link to the dataset?

**Comment by DeweiHu** [comment]
The dataset is private, acquired by handheld OCT device.
________________________________
From: xwt11 ***@***.***>
Sent: Monday, January 16, 2023 11:08 PM
To: DeweiHu/OCT_DDPM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DeweiHu/OCT_DDPM] Paper's dataset (Issue #4)


Is the dataset in the paper public or private? If it is public, can you provide the link to the dataset?
