### ISSUE TITLE
What paper goes with this code?

### ISSUE THREAD

**Issue by JeffFessler** [DeweiHu/OCT_DDPM#5]
Your readme should say what paper users should cite!

Maybe this one?
https://doi.org/10.1117/12.2612235

**Comment by DeweiHu** [comment]
Yes it is! Thanks for the suggestion, I will complete the readme soon!

Dewei
________________________________
From: Jeff Fessler ***@***.***>
Sent: Thursday, February 2, 2023 3:24 PM
To: DeweiHu/OCT_DDPM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DeweiHu/OCT_DDPM] What paper goes with this code? (Issue #5)


Your readme should say what paper users should cite!

Maybe this one?
https://doi.org/10.1117/12.2612235<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1117%2F12.2612235&data=05%7C01%7Cdewei.hu%40vanderbilt.edu%7C85d889b7d1814c2dfca608db0563d9f6%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C638109698640539393%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r90TqCCNr%2FcbzDP0w38CP1dcINnPa%2B3qTDiqqEDhQns%3D&reserved=0>
